name: 'Build Solution'
description: 'Builds the solution using Visual Studio'
inputs:
  run-tests:
    required: false
    description: 'Run tests after building the solution'
    default: 'true'
  api-key:
    required: false
    description: 'API Key for the tests'
  private-key:
    required: false
    description: 'Private Key for the tests'
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 8.0.x

    - name: Restore Dependencies
      shell: ''
      run: dotnet restore

    - name: Run Tests
      if: ${{ inputs.run-tests == 'true' }}
      shell: ''
      run: dotnet test --logger:"console;verbosity=normal"
      env:
        ForwarderUrl: https://dev.api.vbase.com/forwarder
        ApiKey: ${{ inputs.api-key }}
        PrivateKey: ${{ inputs.private-key }}

    # vswhere helps us to find Visual Studio installation path
    - name: Install vswhere
      shell: ''
      run: choco install vswhere

    # Find Visual Studio installation path
    - name: Find Visual Studio
      id: vs
      shell: ''
      run: |
        vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        echo "vs-path=$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath)" >> $GITHUB_OUTPUT

    # Workaround for a known issue with building a Visual Studio Installer project from the command line
    # See: https://marketplace.visualstudio.com/items?itemName=UnniRavindranathan-MSFT.MicrosoftVisualStudio2013InstallerProjects
    - name: Disable Out of Proc Build (fix for HRESULT = 8000000A)
      working-directory: ${{ steps.vs.outputs.vs-path }}\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild
      shell: cmd
      run: DisableOutOfProcBuild.exe

    # Build the solution
    # Note: We are using devenv.com instead of msbuild
    # because the Visual Studio Installer project does not support msbuild
    - name: Build Solution
      shell: ''
      run: |
        $vsPath = '${{ steps.vs.outputs.vs-path }}'
        & "$vsPath\Common7\IDE\devenv.com" vBase.sln /Build "Release"
