name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 
    
    env:
      Solution_Name: vBase.sln
      Test_Project_Path: vBase.Core.Tests\vBase.Core.Tests.csproj
      ForwarderUrl: https://dev.api.vbase.com/forwarder
      ApiKey: ${{ secrets.API_KEY }}
      PrivateKey: ${{ secrets.PRIVATE_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Install vswhere
      run: choco install vswhere

    - name: Find Visual Studio
      id: vs
      run: |
        vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
        echo "::set-output name=vs-path::$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath)"

    - name: Disable Out of Proc Build (fix for HRESULT = 8000000A)
      run: |
        $vsPath = '${{ steps.vs.outputs.vs-path }}'
        & cd "$vsPath\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild"
        & DisableOutOfProcBuild.exe

    - name: Build Solution
      run: |
        $vsPath = '${{ steps.vs.outputs.vs-path }}'
        & "$vsPath\Common7\IDE\devenv.com" vBase.sln /Build "Release"

    - name: Publish Installer
      uses: actions/upload-artifact@v4
      with:
        name: vBase Setup
        path: vBase.ComShim.Setup\Release\
