name: Update the Main Docs Repository

on:
  # allows manual trigger
  workflow_dispatch:
  push:
    branches:
      - main # publish the docs only when the main branch is updated

jobs:
  update-main-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: |
                8.0.x
                4.8.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      
      # build solution using with msbuild
      - name: Build Solution
        run: msbuild

      # list all the files in the repository
      - name: List Files
        run: |
          ls -R
     
      - name: Publish Documents
        uses: validityBase/docs/publish-docs-action@main
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          target-repository-branch: vbase-py-samples-test
