name: Update the Main Docs Repository

on:
  push:
    #branches:
    #  - main

jobs:
  update-main-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Documents
        uses: validityBase/vbase-cs/publish-product-documentation@docs_repo_build_pipeline
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }} # required
          source-docs-path: 'Docs' # optional - default is 'docs'
          #target-docs-path: # optional - default is the name of the current repository
          target-repository: 'volodymyr-bobko/docs' # optional - default is 'validityBase/docs'
          #target-repository-branch: # optional - default is the branch name of the current product branch
          #preprocess-plant-uml: # optional - default is 'true'
          

