name: Update the Main Docs Repository

on:
  # allows manual trigger
  workflow_dispatch:
  push:
    branches:
      - main # publish the docs only when the main branch is updated

permissions:
  contents: read

jobs:
  update-main-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Node.js (for Docs patch script)
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: "20"

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57

      - name: Restore nuget  packages for the solution
        run: nuget restore vBase.sln

      # Build the solution using MSBuild
      # The goal is to run a minimal build process required to generate the documentation
      # No post-build events will be executed
      - name: Build Solution
        run: msbuild /p:PreBuildEvent= /p:PostBuildEvent=

      # we need to patch the autogenerated MD files
      # to make them compatible with GitBook
      # 1 - all tags should be lowercase eg
      # - [AssemblyResolver](#T-vBase-Infrastructure-AssemblyResolver 'vBase.Infrastructure.AssemblyResolver')
      # should be replaced with
      # - [AssemblyResolver](#t-vbase-infrastructure-assemblyresolver 'vBase.Infrastructure.AssemblyResolver')
      # 2 - anchors should be moved next to the title eg
      # <a name='T-vBase-Infrastructure-AssemblyResolver'></a>
      # ## AssemblyResolver `type`
      # should be replaced with
      # ## AssemblyResolver `type` <a name='t-vbase-infrastructure-assemblyResolver'></a>
      # 3 - all anchors should be extended with id and href attributes eg
      # <a name='T-vBase-Infrastructure-AssemblyResolver'></a>
      # should be replaced with
      # <a id='t-vbase-infrastructure-assemblyresolver' name='t-vbase-infrastructure-assemblyresolver' href='#t-vbase-infrastructure-assemblyresolver'></a>
      - name: Patch MDs in Docs to fix GitBook compatibility
        run: node ./.github/workflows/patch-ms.js

      - name: Publish Documents
        uses: validityBase/vbase-github-actions/.github/actions/publish-docs@v1
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: Docs
          target-repository-branch: main
