name: Update the Main Docs Repository

on:
  push:
    #branches:
    #  - main

jobs:
  update-main-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Documents
        uses: validityBase/vbase-cs/publish-product-documentation@docs_repo_build_pipeline
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: 'Docs'
          target-repository: 'volodymyr-bobko/docs'
