name: Update the Main Docs Repository

on:
  push:
    #branches:
    #  - main

jobs:
  update-main-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build repo docs
        uses: validityBase/vbase-cs/build-repo-docs-action@docs_repo_build_pipeline
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: 'Docs'
